.PHONY: clean All

All:
	@echo "----------Building project:[ INTP - Release ]----------"
	@"$(MAKE)" -f  "INTP.mk"
clean:
	@echo "----------Cleaning project:[ INTP - Release ]----------"
	@"$(MAKE)" -f  "INTP.mk" clean
